# Generated by Django 6.0.3 on 2026-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex rang kodi', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['-usage_count'], name='tags_tag_usage_c_be8d76_idx'), models.Index(fields=['slug'], name='tags_tag_slug_dcb0c2_idx')],
            },
        ),
    ]
