# Generated by Django 6.0.3 on 2026-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioproject',
            name='settings_data',
            field=models.JSONField(default=dict),
        ),
    ]
