# Generated by Django 6.0.3 on 2026-08-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('feed_editor', 'Feed post ↔ Editor'), ('asset_studio', 'Marketplace Asset ↔ Studio'), ('video_project', 'Video ↔ Project'), ('map_project', 'World Map ↔ Project')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='contenttypes.contenttype')),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('link_type', 'source_ct', 'source_id', 'target_ct', 'target_id')},
            },
        ),
    ]
