# Generated by Django 6.0.3 on 2026-03-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('project_apply', '📨 Loyihaga ariza'), ('project_approved', '✅ Arizangiz qabul qilindi'), ('project_rejected', '❌ Arizangiz rad etildi'), ('project_member', "👥 Yangi a'zo qo'shildi"), ('project_created', '🚀 Yangi loyiha'), ('task_assigned', '📋 Vazifa belgilandi'), ('task_completed', '✓ Vazifa bajarildi'), ('asset_liked', '❤️ Aktivingizga like'), ('asset_downloaded', '⬇️ Aktivingiz yuklandi'), ('order_placed', '🛒 Yangi buyurtma'), ('order_completed', '✅ Buyurtma bajarildi'), ('review_received', '⭐ Yangi sharh'), ('system', '🔔 Tizim xabari'), ('mention', '@ Eslatilish')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
