# Generated by Django 6.0.4 on 2026-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('project_apply', '📨 Loyihaga ariza'), ('project_approved', '✅ Arizangiz qabul qilindi'), ('project_rejected', '❌ Arizangiz rad etildi'), ('project_member', "👥 Yangi a'zo qo'shildi"), ('project_created', '🚀 Yangi loyiha'), ('task_assigned', '📋 Vazifa belgilandi'), ('task_completed', '✓ Vazifa bajarildi'), ('asset_liked', '❤️ Aktivingizga like'), ('asset_downloaded', '⬇️ Aktivingiz yuklandi'), ('asset_approved', '✅ Aktivingiz tasdiqlandi'), ('asset_rejected', '❌ Aktivingiz rad etildi'), ('order_placed', '🛒 Yangi buyurtma'), ('order_completed', '✅ Buyurtma bajarildi'), ('review_received', '⭐ Yangi sharh'), ('system', '🔔 Tizim xabari'), ('mention', '@ Eslatilish')], default='system', max_length=30),
        ),
    ]
