# Generated by Django 6.0.4 on 2026-06-13 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Jam',
                'verbose_name_plural': 'Game Jams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='jams/submissions/')),
                ('demo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_submissions', to=settings.AUTH_USER_MODEL)),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jams.jam')),
            ],
            options={
                'verbose_name': 'Jam Submission',
                'verbose_name_plural': 'Jam Submissions',
                'ordering': ['-votes', '-created_at'],
                'unique_together': {('jam', 'creator')},
            },
        ),
    ]
