# Generated by Django 6.0.3 on 2026-06-25 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='game_engine/thumbnails/')),
                ('genre', models.CharField(choices=[('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('shooter', 'Shooter'), ('rpg', 'RPG'), ('arcade', 'Arcade'), ('adventure', 'Adventure'), ('strategy', 'Strategy'), ('other', 'Other')], default='other', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('engine_version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Project',
                'verbose_name_plural': 'Game Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Play Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('build_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Build',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('sprite', 'Sprite / Image'), ('audio', 'Audio / Sound'), ('tilemap', 'Tilemap'), ('font', 'Font'), ('script', 'Script File'), ('other', 'Other')], default='sprite', max_length=20)),
                ('file', models.FileField(upload_to='game_engine/assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='game_engine/asset_thumbs/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Asset',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Scene', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('scene_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Scene',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script_type', models.CharField(choices=[('behavior', 'Behavior Script'), ('event', 'Event Handler'), ('global', 'Global Script')], default='behavior', max_length=20)),
                ('code', models.TextField(blank=True, default='// Write your game logic here\n')),
                ('node_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Script',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_likes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='game_engine.gameproject')),
            ],
            options={
                'verbose_name': 'Game Like',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
