# Generated by Django 6.0.3 on 2026-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefile',
            name='binary_file',
            field=models.FileField(blank=True, null=True, upload_to='workspace_files/'),
        ),
    ]
