# Generated by Django 6.0.3 on 2026-04-24 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_cartitem_purchasedasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='only_for_user',
            field=models.ForeignKey(blank=True, help_text="Faqat ushbu foydalanuvchi ko'ra oladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
