# Generated by Django 6.0.4 on 2026-09-04 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_only_for_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='format',
            field=models.CharField(choices=[('glb', 'GLB (.glb)'), ('gltf', 'GLTF (.gltf, .zip)'), ('obj', 'Wavefront OBJ (.obj)'), ('fbx', 'FBX (.fbx)'), ('blend', 'Blender (.blend)'), ('png', 'PNG Rasm (.png)'), ('jpg', 'JPEG Rasm (.jpg, .jpeg)'), ('tga', 'TGA Tekstura (.tga)'), ('psd', 'Photoshop (.psd)'), ('mp3', 'MP3 Audio (.mp3)'), ('wav', 'WAV Audio (.wav)'), ('ogg', 'OGG Audio (.ogg)'), ('zip', 'ZIP Arxiv (.zip, .rar, .7z)'), ('unitypackage', 'Unity Paket (.unitypackage)'), ('other', 'Boshqa format')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
