# Generated by Django 6.0.4 on 2026-09-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='animation_preview',
            field=models.FileField(blank=True, help_text='Animatsiya preview uchun GIF yoki MP4 fayl', null=True, upload_to='assets/previews/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('3d_asset', '3D Assetlar'), ('animation', 'Animatsiyalar'), ('template', 'Shablonlar / Templates'), ('software', 'Dasturlar / Software'), ('project', 'Loyihalar / Projects'), ('startup', 'Startuplar'), ('plugin', 'Plugin & Extension')], db_index=True, default='3d_asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='format',
            field=models.CharField(choices=[('glb', 'GLB (.glb)'), ('gltf', 'GLTF (.gltf, .zip)'), ('obj', 'Wavefront OBJ (.obj)'), ('fbx', 'FBX (.fbx)'), ('blend', 'Blender (.blend)'), ('gif', 'GIF Animatsiya (.gif)'), ('mp4', 'MP4 Video (.mp4)'), ('webm', 'WebM Video (.webm)'), ('spritesheet', 'Sprite Sheet (.png/.zip)'), ('png', 'PNG Rasm (.png)'), ('jpg', 'JPEG Rasm (.jpg, .jpeg)'), ('tga', 'TGA Tekstura (.tga)'), ('psd', 'Photoshop (.psd)'), ('mp3', 'MP3 Audio (.mp3)'), ('wav', 'WAV Audio (.wav)'), ('ogg', 'OGG Audio (.ogg)'), ('zip', 'ZIP Arxiv (.zip, .rar, .7z)'), ('unitypackage', 'Unity Paket (.unitypackage)'), ('exe', 'Bajariladigan fayl (.exe, .apk)'), ('other', 'Boshqa format')], default='other', max_length=20),
        ),
    ]
