# Generated by Django 6.0.3 on 2026-04-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_user_level_user_xp_useractivity_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free (Client Only)'), ('gold', 'Gold Creator'), ('platinum', 'Platinum Professional')], default='free', max_length=20),
        ),
    ]
