# Generated by Django 6.0.3 on 2026-04-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('deposit', "Hisobni to'ldirish"), ('withdrawal', 'Pul yechish'), ('purchase', 'Sotib olish'), ('sale', 'Sotish (Daromad)'), ('escrow_lock', 'Escrowda muzlatish'), ('escrow_release', 'Escrowdan chiqarish'), ('escrow_refund', 'Escrowdan qaytarish'), ('subscription', "Obuna uchun to'lov")], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
