# Generated by Django 6.0.3 on 2026-05-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0003_job_skills_needed_job_jobs_job_status_57b86b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('xp_gained', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='github_repos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='repos_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('project', 'Loyiha yaratdi'), ('asset', 'Aktiv yukladi'), ('post', "Feedga post qo'shdi"), ('comment', 'Izoh qoldirdi'), ('task', 'Vazifa bajardi'), ('course_complete', 'Kursni tugatdi'), ('job_complete', 'Ishni yakunladi'), ('challenge', 'Challenge bajardi')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['user', 'name'], name='accounts_sk_user_id_3bf8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='accounts_tr_user_id_cfd094_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='accounts_tr_transac_9f7758_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-xp'], name='accounts_us_xp_4c3e95_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='accounts_us_created_d650d4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_type'], name='accounts_us_subscri_4039f5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_506163_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='accounts_us_activit_8a5b92_idx'),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyleaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='freelancerreview',
            index=models.Index(fields=['worker', '-created_at'], name='accounts_fr_worker__a97c00_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyleaderboard',
            index=models.Index(fields=['week_start', 'rank'], name='accounts_we_week_st_e74f85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyleaderboard',
            unique_together={('user', 'week_start')},
        ),
    ]
