# Generated by Django 6.0.3 on 2026-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free — $0/oy'), ('pro', 'Pro — $9/oy'), ('studio', 'Studio — $25/oy'), ('enterprise', 'Enterprise — Custom'), ('gold', 'Gold Creator'), ('platinum', 'Platinum Professional')], default='free', max_length=20),
        ),
    ]
