# Generated by Django 6.0.4 on 2026-06-13 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_stripe_customer_id_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', "Hisobni to'ldirish"), ('withdrawal', 'Pul yechish'), ('purchase', 'Sotib olish'), ('sale', 'Sotish (Daromad)'), ('escrow_lock', 'Escrowda muzlatish'), ('escrow_release', 'Escrowdan chiqarish'), ('escrow_refund', 'Escrowdan qaytarish'), ('subscription', "Obuna uchun to'lov"), ('prize', 'Tournament mukofoti'), ('refund', 'Qaytarish')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance (Wallet)',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free — $0/oy'), ('pro', 'Pro — $9/oy'), ('studio', 'Studio — $25/oy'), ('enterprise', 'Enterprise — Custom')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('past_due', "Muddati o'tgan (to'lov kutilmoqda)"), ('canceled', 'Bekor qilingan'), ('trialing', 'Sinov muddati'), ('inactive', 'Faol emas')], default='inactive', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'indexes': [models.Index(fields=['status'], name='accounts_su_status_c9057c_idx'), models.Index(fields=['plan'], name='accounts_su_plan_4ec127_idx')],
            },
        ),
    ]
