# Generated by Django 6.0.3 on 2026-07-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transaction_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('studio', 'Studio'), ('enterprise', 'Enterprise'), ('gold', 'Pro'), ('platinum', 'Studio')], default='free', max_length=20),
        ),
    ]
