# Generated by Django 6.0.3 on 2026-07-24 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('deposit', 'Depazit'), ('earnings', 'Foyda')], max_length=10)),
                ('action_type', models.CharField(choices=[('credit', "Qo'shish (+)"), ('debit', 'Ayirish (-)'), ('refund', 'Qaytarish'), ('correction', 'Xato tuzatish')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=20)),
                ('reason', models.TextField(verbose_name='Sabab (majburiy)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Hamyon Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'verbose_name': 'User Wallet (Dual Balance)'},
        ),
        migrations.RenameField(
            model_name='userbalance',
            old_name='usd_balance',
            new_name='deposit_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_type',
            field=models.CharField(choices=[('deposit', 'Depazit hamyon'), ('earnings', 'Foyda hamyon'), ('both', 'Ikkalasi')], default='deposit', max_length=10),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='earnings_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', "Depazit to'ldirish"), ('withdrawal', 'Pul yechish (foyda)'), ('purchase', 'Sotib olish'), ('sale', 'Sotish (Daromad)'), ('escrow_lock', 'Escrowda muzlatish'), ('escrow_release', 'Escrowdan chiqarish'), ('escrow_refund', 'Escrowdan qaytarish'), ('subscription', "Obuna uchun to'lov"), ('prize', 'Tournament mukofoti'), ('refund', 'Qaytarish'), ('transfer_to_deposit', "Foydadan Depazitga o'tkazma"), ('admin_adjustment', 'Admin tomonidan tuzatish')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet_type'], name='accounts_tr_wallet__a17d0d_idx'),
        ),
        migrations.AddField(
            model_name='adminwalletauditlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='adminwalletauditlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='adminwalletauditlog',
            index=models.Index(fields=['target_user', '-created_at'], name='accounts_ad_target__937f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwalletauditlog',
            index=models.Index(fields=['admin', '-created_at'], name='accounts_ad_admin_i_2edc00_idx'),
        ),
    ]
