# Generated by Django 6.0.3 on 2026-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='media_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='video_filter',
            field=models.CharField(blank=True, default='none', max_length=500),
        ),
    ]
