# Generated by Django 6.0.3 on 2026-06-29 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🖼️', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='studio_3d/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='studio_3d/thumbs/')),
                ('format', models.CharField(choices=[('texture', 'Texture'), ('concept', 'Concept Art'), ('icon', 'Icon'), ('banner', 'Banner'), ('model', '3D Model')], default='model', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_3d_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio_3d.assetcategory')),
            ],
            options={
                'verbose_name': '3D Asset',
                'verbose_name_plural': '3D Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Scene', max_length=200)),
                ('template', models.CharField(choices=[('empty', "Bo'sh sahna"), ('showcase', 'Showcase'), ('terrain', 'Terrain'), ('room', 'Room'), ('space', 'Space'), ('city', 'City'), ('nature', 'Nature'), ('abstract', 'Abstract')], default='empty', max_length=30)),
                ('scene_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes_3d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
