# Generated by Django 6.0.4 on 2026-08-31 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset3d',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset3d',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Bytes'),
        ),
        migrations.AddField(
            model_name='asset3d',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene3d',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene3d',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='studio_3d/scene_thumbs/'),
        ),
        migrations.AlterField(
            model_name='asset3d',
            name='file',
            field=models.FileField(upload_to='studio_3d/models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'obj'])]),
        ),
        migrations.AlterField(
            model_name='asset3d',
            name='format',
            field=models.CharField(choices=[('glb', 'GLB (Binary glTF)'), ('gltf', 'glTF'), ('obj', 'OBJ')], default='glb', max_length=10),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='icon',
            field=models.CharField(default='cube', max_length=50),
        ),
        migrations.AlterField(
            model_name='scene3d',
            name='template',
            field=models.CharField(choices=[('empty', "Bo'sh sahna"), ('showcase', 'Showcase (Vitrina)'), ('terrain', 'Terrain'), ('room', 'Xona (Room)'), ('space', 'Kosmik muhit'), ('nature', 'Tabiat'), ('abstract', 'Abstrakt')], default='empty', max_length=30),
        ),
    ]
