# Generated by Django 6.0.3 on 2026-03-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('developer', '💻 Developer'), ('artist', '🎨 3D Artist'), ('animator', '🎬 Animator'), ('designer', '✏️ UI/UX Designer'), ('sound', '🎵 Sound Designer'), ('producer', '📋 Producer'), ('qa', '🧪 QA Engineer'), ('writer', '📝 Writer/Narrative'), ('marketing', '📣 Marketing'), ('other', '🔧 Boshqa')], max_length=30)),
                ('job_type', models.CharField(choices=[('fulltime', "To'liq stavka"), ('parttime', 'Qisman stavka'), ('contract', 'Shartnoma'), ('volunteer', 'Ixtiyoriy'), ('freelance', 'Freelance')], default='parttime', max_length=20)),
                ('status', models.CharField(choices=[('open', '✅ Ochiq'), ('closed', '❌ Yopiq'), ('filled', '🎉 Band')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('skills_needed', models.CharField(blank=True, max_length=300)),
                ('is_paid', models.BooleanField(default=False)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('portfolio_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Kutilmoqda'), ('reviewed', "👀 Ko'rib chiqildi"), ('accepted', '✅ Qabul qilindi'), ('rejected', '❌ Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
