# Generated by Django 6.0.3 on 2026-05-05 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobpost_posted_by_remove_jobpost_project_job_and_more'),
        ('projects', '0002_remove_project_tech_stack_and_more'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_needed',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='tags.tag'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client', '-created_at'], name='jobs_job_client__3fc1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['selected_worker'], name='jobs_job_selecte_bed16a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['visibility', 'status'], name='jobs_job_visibil_7bde0a_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['job', 'status'], name='jobs_propos_job_id_b19e65_idx'),
        ),
    ]
