# Generated by Django 6.0.3 on 2026-05-22 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('map_type', models.CharField(choices=[('dungeon', 'Dungeon Planning'), ('village', 'Village Planning'), ('castle', 'Castle Layout'), ('level', 'Level Design'), ('architecture', 'Architecture Sketch')], default='level', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Serialized map grid/sketch data')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='world_builder/thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
