# Generated by Django 6.0.4 on 2026-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldmap',
            name='map_type',
            field=models.CharField(choices=[('dungeon', 'Dungeon Planning'), ('village', 'Village Planning'), ('castle', 'Castle Layout'), ('level', 'Level Design'), ('architecture', 'Architecture Sketch'), ('overworld', 'Overworld & Kingdoms'), ('wilderness', 'Wilderness & Forest'), ('desert', 'Desert & Ruins'), ('coastal', 'Coastal & Islands')], default='level', max_length=50),
        ),
    ]
