# Generated by Django 6.0.3 on 2026-05-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0002_enhanced_image_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagelayer',
            name='unique_layer_name_per_project',
        ),
        migrations.RenameIndex(
            model_name='imageproject',
            new_name='image_edito_owner_i_dfd5d1_idx',
            old_name='image_editor_owner_idx',
        ),
        migrations.RemoveField(
            model_name='imageproject',
            name='image',
        ),
        migrations.AlterUniqueTogether(
            name='imagelayer',
            unique_together={('project', 'name')},
        ),
    ]
