# Generated by Django 6.0.3 on 2026-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='feed/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', '📝 Matn'), ('image', '🖼️ Rasm'), ('video', '🎥 Video'), ('snippet', '💻 Kod Snippet'), ('project', '🚀 Loyiha ulashish'), ('asset', '📦 Aktiv ulashish')], default='text', max_length=20),
        ),
    ]
