# Generated by Django 6.0.3 on 2026-03-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('rpg', 'RPG'), ('strategy', 'Strategiya'), ('puzzle', 'Puzzle'), ('simulation', 'Simulyatsiya'), ('horror', 'Horror'), ('platformer', 'Platformer'), ('other', 'Boshqa')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirish'), ('active', 'Aktiv'), ('completed', 'Yakunlangan'), ('paused', "To'xtatilgan")], default='planning', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Ochiq'), ('private', 'Yopiq'), ('invite', 'Taklif bilan')], default='public', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.CharField(blank=True, help_text='Unity, Blender, React ...', max_length=500)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('developer', "O'yin Dasturchisi"), ('programmer', 'Dasturchi'), ('artist', '3D Rassom'), ('designer', 'Dizayner'), ('sound', 'Musiqa/Ovoz'), ('writer', 'Stsenariy Yozuvchi'), ('other', 'Boshqa')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.CharField(blank=True, max_length=200)),
                ('is_filled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Bajarilishi kerak'), ('inprogress', 'Jarayonda'), ('done', 'Bajarildi')], default='todo', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Ariza xabari')),
                ('is_approved', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectrole')),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
