# Generated by Django 6.0.3 on 2026-05-05 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator', '-created_at'], name='projects_pr_creator_bbe982_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', 'status'], name='projects_pr_visibil_23f1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'is_approved'], name='projects_pr_project_ed34bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='projects_ta_project_cd2085_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='projects_ta_assigne_6bc973_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tags.tag'),
        ),
    ]
