# Generated by Django 6.0.4 on 2026-09-17 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_tech_stack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_enabled',
            field=models.BooleanField(default=False, help_text='Loyihani yuklab olish yoqilganmi?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, help_text='Yuklab olinadigan loyiha fayli (ZIP, RAR va boshqalar)', null=True, upload_to='project_files/'),
        ),
        migrations.CreateModel(
            name='ProjectDownloadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_download_permissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_permissions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'user'], name='projects_pr_project_88caee_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
