# Generated by Django 6.0.3 on 2026-05-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_freelancerreview_weeklyleaderboard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('weekly', '🗓️ Haftalik'), ('monthly', '📅 Oylik'), ('special', '⭐ Maxsus'), ('beginner', '🌱 Yangi boshlagan')], default='weekly', max_length=10)),
                ('action_type', models.CharField(choices=[('post', 'Post yozish'), ('project', 'Loyiha yaratish'), ('asset', 'Aktiv yuklash'), ('job_complete', 'Ishni yakunlash'), ('course', 'Kurs tugatish'), ('comment', 'Izoh qoldirish'), ('follow', "Obunachilar qo'shish"), ('cert', 'Sertifikat olish')], max_length=20)),
                ('target_count', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.badge')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['is_active', '-start_date'], name='challenges__is_acti_ba3744_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['end_date'], name='challenges__end_dat_5dedbb_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['user', 'completed'], name='challenges__user_id_24156f_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge', 'completed'], name='challenges__challen_2896df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('challenge', 'user')},
        ),
    ]
